/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateDocumentImageRouteImport } from './routes/api/generate-document-image'
import { Route as ApiPublicHooksGenerateReelsRouteImport } from './routes/api/public/hooks/generate-reels'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateDocumentImageRoute =
  ApiGenerateDocumentImageRouteImport.update({
    id: '/api/generate-document-image',
    path: '/api/generate-document-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateReelsRoute =
  ApiPublicHooksGenerateReelsRouteImport.update({
    id: '/api/public/hooks/generate-reels',
    path: '/api/public/hooks/generate-reels',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/generate-document-image': typeof ApiGenerateDocumentImageRoute
  '/api/public/hooks/generate-reels': typeof ApiPublicHooksGenerateReelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/generate-document-image': typeof ApiGenerateDocumentImageRoute
  '/api/public/hooks/generate-reels': typeof ApiPublicHooksGenerateReelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/generate-document-image': typeof ApiGenerateDocumentImageRoute
  '/api/public/hooks/generate-reels': typeof ApiPublicHooksGenerateReelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/update-password'
    | '/api/generate-document-image'
    | '/api/public/hooks/generate-reels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/update-password'
    | '/api/generate-document-image'
    | '/api/public/hooks/generate-reels'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/update-password'
    | '/api/generate-document-image'
    | '/api/public/hooks/generate-reels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ApiGenerateDocumentImageRoute: typeof ApiGenerateDocumentImageRoute
  ApiPublicHooksGenerateReelsRoute: typeof ApiPublicHooksGenerateReelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-document-image': {
      id: '/api/generate-document-image'
      path: '/api/generate-document-image'
      fullPath: '/api/generate-document-image'
      preLoaderRoute: typeof ApiGenerateDocumentImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-reels': {
      id: '/api/public/hooks/generate-reels'
      path: '/api/public/hooks/generate-reels'
      fullPath: '/api/public/hooks/generate-reels'
      preLoaderRoute: typeof ApiPublicHooksGenerateReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiGenerateDocumentImageRoute: ApiGenerateDocumentImageRoute,
  ApiPublicHooksGenerateReelsRoute: ApiPublicHooksGenerateReelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
