// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // Fall back to hardcoded values as a last resort to ensure the app loads
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 
                       (typeof process !== 'undefined' ? (process.env.EXT_SUPABASE_URL || process.env.SUPABASE_URL) : undefined) ||
                       "https://esujxypnyfhcxhfeqpii.supabase.co";
                       
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
                                   (typeof process !== 'undefined' ? (process.env.EXT_SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY) : undefined) ||
                                   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdWp4eXBueWZoY3hoZmVxcGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMDk5OTcsImV4cCI6MjA5Mzg4NTk5N30.e5v6l6FY02NX76BDyf6Mqqf3ZLRVk7ShS4Sn758pvGw";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (typeof window === 'undefined') {
      // Return a dummy client for SSR if keys are missing
      // This avoids crashing during the pre-hydration pass
      return {} as any;
    }
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
